version: '3'
services:
  data-source:
    build:
      context: ./data-source-flask
      dockerfile: Dockerfile_data_source
    environment:
      - KAFKA_BROKER_URL=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: "exit 0"
      interval: 5s
      retries: 10
      start_period: 30s

  data-ingestion:
    build:
      context: ./data-ingestion-kafka
      dockerfile: Dockerfile_data_ingestion
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BROKER_URL=kafka:9092
    healthcheck:
      test: "exit 0"
      interval: 5s
      retries: 10
      start_period: 30s

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    healthcheck:
      test: "exit 0"
      interval: 5s
      retries: 10
      start_period: 30s

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    healthcheck:
      test: "exit 0"
      interval: 5s
      retries: 10
      start_period: 30s
