FROM python:3.9

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY data_ingestion.py .

# Command to run the data ingestion script
CMD ["python", "data_ingestion.py"]
