# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Environment variables for PostgreSQL configuration
ENV POSTGRES_USER news_user
ENV POSTGRES_PASSWORD news_password
ENV POSTGRES_DB news_db

# Expose the PostgreSQL port
EXPOSE 5432
